package soa4core.examples.negotiationTestNetwork.RT;

import core4inet.nodes.ethernet.avb_AS6802.TTEAVBEtherHost;
import core4inet.incoming.AS6802.TTIncoming;
import core4inet.buffer.AS6802.TTQueueBuffer;
import core4inet.incoming.AS6802.RCIncoming;
import core4inet.buffer.AS6802.RCQueueBuffer;
import soa4core.nodes.MiddlewareHost;


module Subscriber extends MiddlewareHost
{
	submodules:
	connections: 
 
}